Added points to map, playing around with an infowindow
GDSC-OregonState/DamStudy-Frontend pull request #7
Opened 2024-04-15 02:20 UTC by ttlarson7

2024-04-15 03:32 UTC, sebat2004 requested changes
One small fix but the rest LGTM

2024-04-15 03:32 UTC, sebat2004 commented on src/components/explore.tsx
> +
You declared this but didn't end up using it

2024-04-16 01:33 UTC, PotatoPresident approved these changes
LGTM

2024-04-16 01:54 UTC, sebat2004 commented on src/components/explore.tsx
> +
Ah shucks who cares it looks good to Will

2024-04-16 01:54 UTC, sebat2004 approved these changes

2024-04-16 01:55 UTC, merged